# Generated by Django 3.1.7 on 2021-02-21 12:26

import apps.schedule.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.DateTimeField(help_text='Time should atleast 60 minutes from start time', validators=[apps.schedule.validator.val_future_end_time]),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.DateTimeField(help_text='Time should be at least 60 mins before current time', validators=[apps.schedule.validator.val_future_time]),
        ),
    ]
